version: '1.0'
stages:
  - checkout
  - buildimage
  - upload
  - updatetag
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: buildimage
    image_name: test-app
    working_directory: ./
    tag: '${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
    disable_push: false
  MyPushStep:
    title: Pushing to DockerHub Registry
    type: push
    stage: upload
    tag: ${{CF_SHORT_REVISION}}
    candidate: '${{MyAppDockerImage}}'
    image_name: lakal/test-app #Change kkapelon to your dockerhub username
    registry: lakal # Name of your integration as was defined in the Registry screen
  UpdateImage:
    title: update image tag
    type: freestyle
    image: busybox
    stage: updatetag
    commands:
      - sed -i 's/lakal\/test-app/lakal\/test-app-${{CF_SHORT_REVISION}}/g' ./kubernetes/test_deploy.yaml
      - cat ./kubernetes/test_deploy.yaml
  DeployToMyCluster:
    title: deploying to cluster
    type: deploy
    stage: deploy
    kind: kubernetes
    ## cluster name as the shown in account's integration page
    cluster:  test-cluster
    # desired namespace
    namespace: default
    file_path: ./kubernetes/test_deploy.yaml
