apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-app
    spec:
      imagePullSecrets:
        - name: my-docker-secret
      containers:
      - image: lakal/test-app
        imagePullPolicy: Always
        name: test-app
        resources: {}
      restartPolicy: Always
